### ISSUE TITLE
In 3.1 juiste link naar W3C Trace Context opnemen

### ISSUE THREAD

**Issue by ehotting** [Logius-standaarden/logboek-dataverwerkingen#77]
In 3.1 juiste link naar W3C Trace Context opnemen

**Comment by Nil-NMB01** [comment]
@ehotting Om welk document gaat dit?

**Comment by bwbroersma** [comment]
This line:
https://github.com/Logius-standaarden/logboek-dataverwerkingen/blob/0001ef056492883cdf1d8e398c747e8c206ce7f0/sections/03-specificaties/01-protocollen.md#L9

Since [ReSpec references](https://respec.org/docs/#references-0) use the [Specref ecosystem](http://specref.org/), it [looks like](https://www.specref.org/?q=trace%20context) `W3C Trace Context` should be replaced with `[[[trace-context-1]]]`.

**Comment by bwbroersma** [comment]
To nitpick: I'm not sure if `[[[` was the better option over `[[`, since now the text is slightly different (W3C is dropped), and it's inconsistent with the RFC references.
